# Generated by Django 3.0.7 on 2020-06-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('township', models.CharField(blank=True, max_length=10, null=True)),
                ('big_section', models.CharField(blank=True, max_length=100, null=True)),
                ('small_section', models.CharField(blank=True, max_length=100, null=True)),
                ('other_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
