# Generated by Django 3.0.2 on 2020-06-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='縣市')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='big_section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='段號'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=100, verbose_name='案號'),
        ),
        migrations.AlterField(
            model_name='case',
            name='other_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='case',
            name='small_section',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='小段'),
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='鄉鎮區')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.Country', verbose_name='縣市')),
            ],
        ),
        migrations.AlterField(
            model_name='case',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Country', verbose_name='縣市'),
        ),
        migrations.AlterField(
            model_name='case',
            name='township',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.Township', verbose_name='鄉鎮區'),
        ),
    ]
